# Generated by Django 5.2.4 on 2025-08-15 04:02

from django.db import migrations, models
from django.db import connection


def check_and_remove_fields(apps, schema_editor):
    """Verificar si las tablas existen antes de eliminar los campos"""
    with connection.cursor() as cursor:
        # Verificar si las tablas de grupos y permisos existen
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'usuarios_groups'
            );
        """)
        groups_table_exists = cursor.fetchone()[0]
        
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'usuarios_user_permissions'
            );
        """)
        permissions_table_exists = cursor.fetchone()[0]
        
        # Solo eliminar las tablas si existen
        if groups_table_exists:
            cursor.execute("DROP TABLE IF EXISTS usuarios_groups CASCADE;")
        
        if permissions_table_exists:
            cursor.execute("DROP TABLE IF EXISTS usuarios_user_permissions CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0016_alter_usuario_password'),
    ]

    operations = [
        migrations.RunPython(check_and_remove_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$hhhkWgU4I4tVvD1qqAjqf5$sA96/8KhN3CeFUlilQn7J0RPpujsq2zDPL9H36rCEsk=', max_length=128),
        ),
    ]
